name: Deploy workflow

on:
  workflow_call:
    inputs:
      environmentToDeployTo:
        required: true
        type: string
      imageTagToDeploy:
        required: true
        type: string
      issueNumber:
        required: true
        type: number
    secrets:
      TOKEN:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environmentToDeployTo  }}
    env:
      imageTagToDeploy: ${{ inputs.imageTagToDeploy }}
      environmentSpecificTag: ${{ inputs.environmentToDeployTo }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get current date
        id: date
        run: |
          echo "dateval=$(date +'%Y-%m-%d')" >>$GITHUB_OUTPUT
      - name: Update Dashboard
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'update-issue'
          token: ${{ secrets.TOKEN }}
          issue-number: ${{ inputs.issueNumber }}
          state: 'open'
          body: "currently deployed ${{env.environmentSpecificTag}} ${{ github.sha }} ${{ steps.date.outputs.dateval }}"
          update-mode: 'append'
#      - name: Find Comment
#        uses: peter-evans/find-comment@v2
#        id: fc
#        with:
#          issue-number: 1
#          body-includes: "currently deployed dev"
#      - run: |
#          echo ${{ steps.fc.outputs.comment-id }}
#          echo ${{ steps.fc.outputs.comment-body }}
#          echo ${{ steps.fc.outputs.comment-author }}
#          echo ${{ steps.fc.outputs.comment-created-at }}
#      - name: Update comment
#        uses: actions-cool/issues-helper@v3
#        with:
#          actions: 'update-comment'
#          token: ${{ secrets.TOKEN }}
#          issue-number: 1
#          comment-id: "1592555919"
#          body: "currently deployed ${{env.environmentSpecificTag}} ${{ github.sha }}"
#          emoji: 'eyes'