name: Report test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: report-on-branch-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: my-step
        run: echo "Hello World!"
      - name: Update issue
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'update-issue'
          token: ${{ secrets.TOKEN }}
          issue-number: 1
          state: 'open'
          title: 'Updated the issue'
          body: 'new body'
          update-mode: 'replace'
          labels: 'xx'
          emoji: '+1'
